- name: check the number is less than or not
  hosts: local
  connection: local
  var_prompt: 
    - name: number
      prompt: please enter the number
      private: false #not a confidential

  tasks: 
  - name: print if the number is less than
    ansible.builtin.debug:
      msg: " given number {{ number }} is less than 10"
    when: number | int < 10 # conditional expression

  - name: print if the number is grater than or eqaul to 10
    ansible.builtin.debug:
      msg: "given number {{ number }} is greater thn or equal to 10"
    when: number | int >= 10 